description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
    - run: bun install --frozen-lockfile
      shell: bash
  using: composite
