jobs:
  post_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "npm_version=$(cat package.json | grep '"version"' | cut -d'"' -f4)" >> "$GITHUB_ENV"
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :tada: This is included in version {release_link} :tada:

            The release is available on:

            * [GitHub releases](https://github.com/WomB0ComB0/enterprise-ai-recursive-web-scraper/releases/tag/{release_tag})
            * [npm package (@latest dist-tag)](https://www.npmjs.com/package/enterprise-ai-recursive-web-scraper/v/${{ env.npm_version }})

            Cheers! 📦🚀

name: Post Release

permissions:
  contents: read

on:
  release:
    types:
      - published
